name: Black Formatting Lint

on: [push, pull_request]

jobs:
  Black-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check code formatting
        uses: psf/black@stable
        with:
          options: "--check --diff"  # Add the options here

      - name: Display Black output
        run: |
          echo "${{ steps.black.outputs.results }}"
        if: ${{ steps.black.outcome == 'failure' }}